### ISSUE TITLE
withSystemTrustMaterial cannot create TrustStore because certificate is absent

### ISSUE THREAD

**Issue by nquinquenel** [Hakky54/sslcontext-kickstart#367]
**Describe the bug**

We recently released a new version of our product containing your library, and it appears that a lot of users have issues when creating the `SSLFactoryBuilder#withSystemTrustMaterial`.

This results in the error `Could not create TrustStore because certificate is absent`.
One user on Linux has multiple certificates under `/etc/ssl/certs` which is a symlink to `/var/lib/ca-certificates/pem`. For Linux, `/etc/ssl/certs` should be a valid path for certificates given your library source code, which is surprising that it's failing.

**To Reproduce**

I was not able to reproduce it, here is the list of OS on which users have issues:

- Mac OS X x86_64
- macOS 13.5
- openSUSE Tumbleweed 20230801

All use Java 17.0.7.

One is using Zscalar and Global Protect for system security. Zscalar replaces the certs with its own so that it is able to examine the traffic.

Here is the stack trace related to the issue:

`Caused by: java.lang.IllegalArgumentException: Could not create TrustStore because certificate is absent
	at nl.altindag.ssl.util.internal.ValidationUtils.lambda$requireNotEmpty$2(ValidationUtils.java:47)
	at nl.altindag.ssl.util.internal.ValidationUtils.requireNotEmpty(ValidationUtils.java:52)
	at nl.altindag.ssl.util.internal.ValidationUtils.requireNotEmpty(ValidationUtils.java:47)
	at nl.altindag.ssl.util.KeyStoreUtils.createTrustStore(KeyStoreUtils.java:177)
	at nl.altindag.ssl.util.KeyStoreUtils.loadSystemKeyStores(KeyStoreUtils.java:219)
	at nl.altindag.ssl.util.TrustManagerUtils.createTrustManagerWithSystemTrustedCertificates(TrustManagerUtils.java:89)
	at nl.altindag.ssl.SSLFactory$Builder.withSystemTrustMaterial(SSLFactory.java:210)`

**Expected behavior**

A certificate directory should be found, and certificates within this directory should be loaded so the trust store can be created.

How we setup the SSLFactoryBuilder: https://github.com/SonarSource/sonarlint-core/blob/master/http/src/main/java/org/sonarsource/sonarlint/core/http/HttpClientProvider.java#L63

**Comment by Hakky54** [comment]
It seems like somehow on those mac's and linux machines no certificates are found by the library and therefor resulting into this error, which is strange as the Java NIO Files class follows symbolic links. I have not explicitly tested this case with symbolic links, but I will do that in the coming days. The mac's should also have some certificates, but I am not sure whether the user or NPA user which is running the application has the permission to run a process in the background. So a fix will be on the way when I can also reproduce it on my side.

What I can do now is resolve this exception, it will explicitly check whether there are certificates and if none it won't fail. This will only prevent this exception happening ever again. The next step would be resolving the loading of the certificates when I can reproduce it locally. What do you think, are you ok with this approach?

Another option would be coming in touch with your clients which have this issue. I can look while the developer can start the application with a debugger so I can better understand and replicate the issue. This would be more effective as I would get to see the actual issue.

**Comment by nquinquenel** [comment]
Thank you for the quick followup. Here is a different stack trace from a Mac user (Mac OS X):

`Caused by: nl.altindag.ssl.exception.GenericCertificateException: There is no valid certificate present to parse. Please make sure to supply a valid der formatted certificate
	at nl.altindag.ssl.util.CertificateUtils.parseDerCertificate(CertificateUtils.java:261)
	at nl.altindag.ssl.util.CertificateUtils.parseCertificate(CertificateUtils.java:240)
	at nl.altindag.ssl.util.CertificateUtils.parsePemCertificate(CertificateUtils.java:220)
	at nl.altindag.ssl.util.MacCertificateUtils.getCertificates(MacCertificateUtils.java:58)
	at nl.altindag.ssl.util.KeyStoreUtils.loadSystemKeyStores(KeyStoreUtils.java:212)
	at nl.altindag.ssl.util.TrustManagerUtils.createTrustManagerWithSystemTrustedCertificates(TrustManagerUtils.java:89)
	at nl.altindag.ssl.SSLFactory$Builder.withSystemTrustMaterial(SSLFactory.java:210)
	at org.sonarsource.sonarlint.core.http.HttpClientProvider.<init>(HttpClientProvider.java:63)
	at org.sonarsource.sonarlint.core.spring.SonarLintSpringAppConfig.provideHttpClientProvider(SonarLintSpringAppConfig.java:156)
	at org.sonarsource.sonarlint.core.spring.SonarLintSpringAppConfig$$EnhancerBySpringCGLIB$$284a5397.CGLIB$provideHttpClientProvider$6(<generated>)
	at org.sonarsource.sonarlint.core.spring.SonarLintSpringAppConfig$$EnhancerBySpringCGLIB$$284a5397$$FastClassBySpringCGLIB$$51c10aa4.invoke(<generated>)
	at org.sonarsource.sonarlint.shaded.org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.sonarsource.sonarlint.shaded.org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at org.sonarsource.sonarlint.core.spring.SonarLintSpringAppConfig$$EnhancerBySpringCGLIB$$284a5397.provideHttpClientProvider(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.sonarsource.sonarlint.shaded.org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 35 more
Caused by: java.security.cert.CertificateParsingException: Empty issuer DN not allowed in X509Certificates
	at java.base/sun.security.x509.X509CertInfo.parse(X509CertInfo.java:658)
	at java.base/sun.security.x509.X509CertInfo.<init>(X509CertInfo.java:169)
	at java.base/sun.security.x509.X509CertImpl.parse(X509CertImpl.java:1793)
	at java.base/sun.security.x509.X509CertImpl.<init>(X509CertImpl.java:184)
	at java.base/sun.security.x509.X509CertImpl.newX509CertImpl(X509CertImpl.java:310)
	at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:471)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:480)
	at nl.altindag.ssl.util.CertificateUtils.parseDerCertificate(CertificateUtils.java:255)
	... 53 more`

Ideally, a `CertificateParsingException` should not prevent all certificates from being loaded, or at least not break the whole process. This should be reproducible with invalid X509 certificates.

From this stack trace, I can imagine the root cause of all those issues would be invalid certificates. For [Linux](https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/LinuxCertificateUtils.java#L89), we simply return an empty list in case of a parsing error whereas for Mac we throw an exception in some specific scenarios and it is not caught. I think the implementation should be somewhat consistent, meaning we catch the exception, return an empty list and avoid stopping the application in such cases. WDYT?

**Comment by Hakky54** [comment]
Thank you for also sharing the stacktrace for the Mac user. The two issues are clear to me and I already have the PR ready for resolving these issues. I will be releasing a new version today.

> Ideally, a CertificateParsingException should not prevent all certificates from being loaded, or at least not break the whole process. This should be reproducible with invalid X509 certificates.

This is now resolved. It will now only log the exception as a debug statement and continue parsing the next file. It seems like openssl is allowing to create a certifciate with less restrictions. This most likely self signed certficate is imported to the mac os x keychain. Java has strict rules and it seems like the certificate of the end-user had a missing field which was not allowed by java. These kind of certificates are now being ignored by the library.

> I could not reproduce it on Linux as a parsing error simply returns an empty collection for the given certificate path.

In my sutation I always had tructed Certificate Authorities, altough I only tested it on Ubuntu. However if there are no trusted CA's at all within all of the directories which is configured within the library then indeed it will end up with an empty list of certificates. Creating a truststore with an empty list of certificates is not allowed and does also not make sense to allow it. So Now the truststore is only being created if there are any trusted certificates for linux or else it will just ignore it.

> Also, one point I'm not sure about, for Mac OS we go through [MacCertificateUtils#getCertificates](https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/MacCertificateUtils.java#L58) -> [CertificateUtils#parsePemCertificate](https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/CertificateUtils.java#L217) -> [CertificateUtils#parseCertificate](https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/CertificateUtils.java#L237) -> CertificateUtils#parseDerCertificate
>
> Is it expected to parse a DER certificate while being called from a parsePermCertificate method?

The Mac Keychain is being extracted with a shell command which will return the certificates in a Base64 encoded string, also known as a PEM format. Therefor I pass it first to [CertificateUtils#parsePemCertificate](https://github.com/Hakky54/sslcontext-kickstart/blob/master/sslcontext-kickstart/src/main/java/nl/altindag/ssl/util/CertificateUtils.java#L217) which will decode it and it will return a byte array. This byte array needs to be decoded as well to result into a binary form of the certificate also known as DER certificate. I hope it make sense. PEM is just a different format for the DER/binary certificate.

**Comment by Hakky54** [comment]
The fix is now available within version `8.1.5`

**Comment by nquinquenel** [comment]
Splendid, thank you for your rapidity and explanations - as always!

I will get back to you once I have a new build for users to try.

**Comment by nquinquenel** [comment]
Following our new build using version 8.1.5, all the issues seem to be resolved for users.

Although there is another annoying side effect. On MacOS a bash command is triggered to execute the `security find-certificate` command, and it seems to alert antivirus and other security processes.

**Comment by Hakky54** [comment]
Thank you for the follow up! It seems like we made good progress by resolving the two initial issues and it seems like the fix is working.

The side effect is a bit pity, I was not expecting the antivirus to raise this as an issue. In my opinion it is a false-positive as it does nothing malicious, but probable it is just raising an alert as it uses a shell proces in the background to collect the trusted certificate authorities.

Let's continue the discussion on the new issue which your colleague has opened
