### ISSUE TITLE
Remove too verbose logs when loading system certificates

### ISSUE THREAD

**Issue by henryju** [Hakky54/sslcontext-kickstart#492]
Hello @Hakky54 

When configuring the library to load system certificates, I always get these logs:

```
17:06:37.230 DEBUG There is no valid certificate present to parse. Please make sure to supply a valid der formatted certificate
java.security.cert.CertificateException: No certificate data found
	at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:456)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:480)
	at nl.altindag.ssl.util.CertificateUtils.parseDerCertificate(CertificateUtils.java:257)
	at nl.altindag.ssl.util.CertificateUtils.parseCertificate(CertificateUtils.java:204)
	at nl.altindag.ssl.util.CertificateUtils.loadCertificate(CertificateUtils.java:180)
	at nl.altindag.ssl.util.CertificateUtils.loadCertificate(CertificateUtils.java:155)
	at nl.altindag.ssl.util.LinuxCertificateUtils.loadCertificate(LinuxCertificateUtils.java:86)
	at nl.altindag.ssl.util.LinuxCertificateUtils.lambda$getCertificates$2(LinuxCertificateUtils.java:71)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at nl.altindag.ssl.util.LinuxCertificateUtils.getCertificates(LinuxCertificateUtils.java:72)
	at nl.altindag.ssl.util.KeyStoreUtils.loadSystemKeyStores(KeyStoreUtils.java:220)
	at nl.altindag.ssl.util.TrustManagerUtils.createTrustManagerWithSystemTrustedCertificates(TrustManagerUtils.java:93)
	at nl.altindag.ssl.SSLFactory$Builder.withSystemTrustMaterial(SSLFactory.java:213)
	at org.sonarsource.scanner.lib.internal.http.OkHttpClientFactory.configureSsl(OkHttpClientFactory.java:166)
	at org.sonarsource.scanner.lib.internal.http.OkHttpClientFactory.create(OkHttpClientFactory.java:88)
	at org.sonarsource.scanner.lib.internal.http.ServerConnection.init(ServerConnection.java:65)
	at org.sonarsource.scanner.lib.ScannerEngineBootstrapper.bootstrap(ScannerEngineBootstrapper.java:106)
	at org.sonarsource.scanner.cli.Main.analyze(Main.java:76)
	at org.sonarsource.scanner.cli.Main.main(Main.java:64)
17:06:37.234 DEBUG There is no valid certificate present to parse. Please make sure to supply a valid der formatted certificate
java.security.cert.CertificateException: No certificate data found
	at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:456)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:480)
	at nl.altindag.ssl.util.CertificateUtils.parseDerCertificate(CertificateUtils.java:257)
	at nl.altindag.ssl.util.CertificateUtils.parseCertificate(CertificateUtils.java:204)
	at nl.altindag.ssl.util.CertificateUtils.loadCertificate(CertificateUtils.java:180)
	at nl.altindag.ssl.util.CertificateUtils.loadCertificate(CertificateUtils.java:155)
	at nl.altindag.ssl.util.LinuxCertificateUtils.loadCertificate(LinuxCertificateUtils.java:86)
	at nl.altindag.ssl.util.LinuxCertificateUtils.lambda$getCertificates$2(LinuxCertificateUtils.java:71)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at nl.altindag.ssl.util.LinuxCertificateUtils.getCertificates(LinuxCertificateUtils.java:72)
	at nl.altindag.ssl.util.KeyStoreUtils.loadSystemKeyStores(KeyStoreUtils.java:220)
	at nl.altindag.ssl.util.TrustManagerUtils.createTrustManagerWithSystemTrustedCertificates(TrustManagerUtils.java:93)
	at nl.altindag.ssl.SSLFactory$Builder.withSystemTrustMaterial(SSLFactory.java:213)
	at org.sonarsource.scanner.lib.internal.http.OkHttpClientFactory.configureSsl(OkHttpClientFactory.java:166)
	at org.sonarsource.scanner.lib.internal.http.OkHttpClientFactory.create(OkHttpClientFactory.java:88)
	at org.sonarsource.scanner.lib.internal.http.ServerConnection.init(ServerConnection.java:65)
	at org.sonarsource.scanner.lib.ScannerEngineBootstrapper.bootstrap(ScannerEngineBootstrapper.java:106)
	at org.sonarsource.scanner.cli.Main.analyze(Main.java:76)
	at org.sonarsource.scanner.cli.Main.main(Main.java:64)
17:06:37.236 DEBUG There is no valid certificate present to parse. Please make sure to supply a valid der formatted certificate
java.security.cert.CertificateException: No certificate data found
	at java.base/sun.security.provider.X509Factory.parseX509orPKCS7Cert(X509Factory.java:456)
	at java.base/sun.security.provider.X509Factory.engineGenerateCertificates(X509Factory.java:356)
	at java.base/java.security.cert.CertificateFactory.generateCertificates(CertificateFactory.java:480)
	at nl.altindag.ssl.util.CertificateUtils.parseDerCertificate(CertificateUtils.java:257)
	at nl.altindag.ssl.util.CertificateUtils.parseCertificate(CertificateUtils.java:204)
	at nl.altindag.ssl.util.CertificateUtils.loadCertificate(CertificateUtils.java:180)
	at nl.altindag.ssl.util.CertificateUtils.loadCertificate(CertificateUtils.java:155)
	at nl.altindag.ssl.util.LinuxCertificateUtils.loadCertificate(LinuxCertificateUtils.java:86)
	at nl.altindag.ssl.util.LinuxCertificateUtils.lambda$getCertificates$2(LinuxCertificateUtils.java:71)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at nl.altindag.ssl.util.LinuxCertificateUtils.getCertificates(LinuxCertificateUtils.java:72)
	at nl.altindag.ssl.util.KeyStoreUtils.loadSystemKeyStores(KeyStoreUtils.java:220)
	at nl.altindag.ssl.util.TrustManagerUtils.createTrustManagerWithSystemTrustedCertificates(TrustManagerUtils.java:93)
	at nl.altindag.ssl.SSLFactory$Builder.withSystemTrustMaterial(SSLFactory.java:213)
	at org.sonarsource.scanner.lib.internal.http.OkHttpClientFactory.configureSsl(OkHttpClientFactory.java:166)
	at org.sonarsource.scanner.lib.internal.http.OkHttpClientFactory.create(OkHttpClientFactory.java:88)
	at org.sonarsource.scanner.lib.internal.http.ServerConnection.init(ServerConnection.java:65)
	at org.sonarsource.scanner.lib.ScannerEngineBootstrapper.bootstrap(ScannerEngineBootstrapper.java:106)
	at org.sonarsource.scanner.cli.Main.analyze(Main.java:76)
	at org.sonarsource.scanner.cli.Main.main(Main.java:64)
```

Would it be possible to silence that? From experience, users are reporting issues when they see a stacktrace, even if it is just a debug log.

Thanks!

**Comment by Hakky54** [comment]
Hi @henryju 

It seems like it is indeed generating a-lot noise. Have you tried configuring your logger? I noticed you use slf4j-simple in the project https://github.com/SonarSource/sonar-scanner-java-library

An example slf4j simple configuration file would be:

```
org.slf4j.simpleLogger.defaultLogLevel=debug

org.slf4j.simpleLogger.log.nl.altindag.ssl=info

org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss:SSS
```

The above snippet will mute debug logs for this ssl library. Let me know whether this works for you.

**Comment by henryju** [comment]
It might be helpful for users to see debug logs, including what is happening in SSL kickstart. But here this is just too verbose to see multiple times the same stacktrace.
I could just silence `nl.altindag.ssl.util.CertificateUtils` logger, but I am concerned of silencing too much.

Also, this library will be embedded into another tool (Maven, Gradle), where we don't control the logging configuration.

**Comment by Hakky54** [comment]
> Also, this library will be embedded into another tool (Maven, Gradle), where we don't control the logging configuration.

Seems like a good reason, I will adjust it and make a release today

**Comment by Hakky54** [comment]
@henryju I just made a release. It is now available in 8.3.5

**Comment by henryju** [comment]
I wonder if this is not a bit too extreme to totally silence a failure in `parseCertificate`.

Why not rethrow the exception, and let callers decide what to do?

I see that the exception will be ignored in `LinuxCertificateUtils.loadCertificate`, and the comment makes me think this is the right place, since in my case the problem comes from those files:
```
> ll /home/julien.henry/.pki/nssdb/
cert9.db    key4.db     pkcs11.txt
```

**Comment by Hakky54** [comment]
> I wonder if this is not a bit too extreme to totally silence a failure in parseCertificate.
> Why not rethrow the exception, and let callers decide what to do?

I am not sure whether it is too extreme, I initially liked to provide debug details for the end-user so they could know something could not be processed without interrupting their flow when loading multiple certificates but it would not harm to remove it. So I never wanted to throw an exception at that level at all.

> I see that the exception will be ignored in LinuxCertificateUtils.loadCertificate, and the comment makes me think this is the right place

Well the downside is actually the loading part of the certificate happens in a deeper level where it initially also logged the failures. What I could have done was to duplicate the logic and have the duplicate without the logging part, but I didin't wanted to have code duplication.

What we can do is monitor the current behaviour. If there is a need to add back the logging part from the community we can add the logs without stacktrace which will be minimal compared to the initial logs would not generate that much noise. What do you think?

**Comment by henryju** [comment]
> What do you think?

Sounds good to me :)
