### ISSUE TITLE
Trusting a pem certificate

### ISSUE THREAD

**Issue by Athou** [Hakky54/sslcontext-kickstart#55]
**Describe the bug**
Thanks for this library, it looks exactly like what I'm looking for: adding a root certificate as trusted so that HTTPS works for all certificates issued by that root certificate.
I however am not sure how to use it, all examples load both a trust material and an identity material, and I only have a public certificate in the pem format. I thought I'd be able to just call `SSLFactory.builder().withTrustMaterial(buildTrustManager()).build();` but I'm getting an exception.

**To Reproduce**
```
git clone https://github.com/Athou/ssl-test
cd ssl-test
mvn test
```
I then get the following exception
```
javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
        at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1921)
        at sun.security.ssl.SSLSocketImpl.handleException(SSLSocketImpl.java:1904)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1420)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
        at test.SslTest.test(SslTest.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:91)
        at sun.security.validator.Validator.getInstance(Validator.java:181)
        at sun.security.ssl.X509TrustManagerImpl.getValidator(X509TrustManagerImpl.java:312)
        at sun.security.ssl.X509TrustManagerImpl.checkTrustedInit(X509TrustManagerImpl.java:171)
        at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:184)
        at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
        at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1596)
        at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
        at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
        at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
        at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
        at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
        ... 37 more
Caused by: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
        at java.security.cert.PKIXParameters.setTrustAnchors(PKIXParameters.java:200)
        at java.security.cert.PKIXParameters.<init>(PKIXParameters.java:120)
        at java.security.cert.PKIXBuilderParameters.<init>(PKIXBuilderParameters.java:104)
        at sun.security.validator.PKIXValidator.<init>(PKIXValidator.java:89)
```
**Expected behavior**
The test passes since mockserver issues certificates that have the `CertificateAuthorityCertificate.pem` as root, as described here https://www.mock-server.com/mock_server/HTTPS_TLS.html (in the "Ensure MockServer Certificates Are Trusted" section)

**Environmental Data:**
 - Java Version: 8
 - Maven Version: 3.5
- OS: Windows

Any help would be greatly appreciated :)

**Comment by Hakky54** [comment]
Hi Jérémie

Really nice to hear that this library is exactly what you are looking for! And thank sharing an example project, this makes it really easy to debug and help you.

I have cloned your project and tried it locally. The setup looks good to mee. I am not getting the same exception as you, for me it is working and I am getting a 200 response. I am using Mac, so I thought it might behave differently for windows. I added a build script to run your project on a linux and windows environment and everything is still working, see here for the build report: https://github.com/Hakky54/ssl-test/runs/1808227852

I didn't changed your code, it is exactly the same as I forked it. I am using oracle jdk 1.8.241 with maven 3.6.3 and I also tried maven 3.5.0 and that also worked. What you can try is maybe not setting the ssl material at the root level but at the specific connection level. So try changing the following snippet:

from:
```
HttpsURLConnection.setDefaultSSLSocketFactory(sslFactory.getSslSocketFactory());
HttpsURLConnection.setDefaultHostnameVerifier(sslFactory.getHostnameVerifier());
```
to:
```
HttpsURLConnection httpsConnection = (HttpsURLConnection) url.openConnection();
httpsConnection.setSSLSocketFactory(sslFactory.getSslSocketFactory());
httpsConnection.setHostnameVerifier(sslFactory.getHostnameVerifier());
```

**Comment by Athou** [comment]
Thanks for your quick response!
I don't know why it doesn't work on my machine but at least I'm using the library correctly :D

I just tried the example on my home computer and it works fine, so I guess there's something wrong on my work computer. I'll try to find out what, thanks again for your help!

**Comment by Hakky54** [comment]
Great to hear @Athou!

You also mentioned the following:
>I however am not sure how to use it, all examples load both a trust material and an identity material, and I only have a public certificate in the pem format. I thought I'd be able to just call

Adding the identity material is only needed when the server is requesting the client to identify itself, also named mutual authentication or two-way-ssl. In that case you can load the private key and the certificate chain into a keymanager and supply it to the sslfactory and hand it over to your http client.

Feel free to ask anything or if you get stuck!
Good luck by the way!

**Comment by Athou** [comment]
> Great to hear @Athou!
> 
> You also mentioned the following:
> 
> > I however am not sure how to use it, all examples load both a trust material and an identity material, and I only have a public certificate in the pem format. I thought I'd be able to just call
> 
> Adding the identity material is only needed when the server is requesting the client to identify itself, also named mutual authentication or two-way-ssl. In that case you can load the private key and the certificate chain into a keymanager and supply it to the sslfactory and hand it over to your http client. Your setup is required one-way-ssl and the SSLFactory configuration for that use case is good and well configured!
> 
> Feel free to ask anything or if you get stuck!
> Good luck by the way!

Thanks for the clarification!

Regarding the exception, I have Oracle JDK 1.8.0_192 on my work machine. I downloaded the latest OpenJDK version (8u282) and it works fine with that version. It may be a JDK bug then.
