### ISSUE TITLE
Using BC fails with Java 1.8.292+

### ISSUE THREAD

**Issue by Hakky54** [Hakky54/sslcontext-kickstart#76]
stacktrace:
```
Error:  nl.altindag.ssl.util.PemUtilsShould.loadEncryptedIdentityMaterialFromDirectory  Time elapsed: 0.031 s  <<< ERROR!
nl.altindag.ssl.exception.GenericIOException: nl.altindag.ssl.exception.GenericKeyStoreException: java.security.KeyStoreException: Key protection  algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
	at nl.altindag.ssl.util.PemUtilsShould.loadEncryptedIdentityMaterialFromDirectory(PemUtilsShould.java:310)
Caused by: nl.altindag.ssl.exception.GenericKeyStoreException: java.security.KeyStoreException: Key protection  algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
	at nl.altindag.ssl.util.PemUtilsShould.loadEncryptedIdentityMaterialFromDirectory(PemUtilsShould.java:310)
Caused by: java.security.KeyStoreException: Key protection  algorithm not found: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
	at nl.altindag.ssl.util.PemUtilsShould.loadEncryptedIdentityMaterialFromDirectory(PemUtilsShould.java:310)
Caused by: java.security.UnrecoverableKeyException: Encrypt Private Key failed: unrecognized algorithm name: PBEWithSHA1AndDESede
	at nl.altindag.ssl.util.PemUtilsShould.loadEncryptedIdentityMaterialFromDirectory(PemUtilsShould.java:310)
Caused by: java.security.NoSuchAlgorithmException: unrecognized algorithm name: PBEWithSHA1AndDESede
	at nl.altindag.ssl.util.PemUtilsShould.loadEncryptedIdentityMaterialFromDirectory(PemUtilsShould.java:310)
```

See bug report at oracle to get the latest update: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8266261

**Comment by Hakky54** [comment]
Fixed with: https://github.com/Hakky54/sslcontext-kickstart/actions/runs/1155365747
